"""add unique constraint

Revision ID: 462c9128c3c4
Revises: 4ef6fbf0f977
Create Date: 2022-02-16 10:23:59.834035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462c9128c3c4'
down_revision = '4ef6fbf0f977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'day_data', ['day_id'], schema='public')
    op.create_unique_constraint(None, 'hour_data', ['hour_id'], schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hour_data', schema='public', type_='unique')
    op.drop_constraint(None, 'day_data', schema='public', type_='unique')
    # ### end Alembic commands ###
