"""add missed fields

Revision ID: 51dee0c3b3c2
Revises: 5f1bc06ab7ff
Create Date: 2022-02-16 11:11:02.140104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51dee0c3b3c2'
down_revision = '5f1bc06ab7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_data', sa.Column('wind_gust', sa.Float(), nullable=True))
    op.drop_constraint('day_feels_like_day_id_fkey', 'day_feels_like', type_='foreignkey')
    op.create_foreign_key(None, 'day_feels_like', 'day_data', ['day_id'], ['day_id'], source_schema='public', referent_schema='public')
    op.drop_constraint('day_temperature_day_id_fkey', 'day_temperature', type_='foreignkey')
    op.create_foreign_key(None, 'day_temperature', 'day_data', ['day_id'], ['day_id'], source_schema='public', referent_schema='public')
    op.drop_constraint('day_weather_day_id_fkey', 'day_weather', type_='foreignkey')
    op.create_foreign_key(None, 'day_weather', 'day_data', ['day_id'], ['day_id'], source_schema='public', referent_schema='public')
    op.add_column('hour_data', sa.Column('pop', sa.Float(), nullable=True))
    op.add_column('hour_data', sa.Column('rain_1h', sa.Float(), nullable=True))
    op.add_column('hour_data', sa.Column('show_1h', sa.Float(), nullable=True))
    op.drop_constraint('hour_weather_hour_id_fkey', 'hour_weather', type_='foreignkey')
    op.create_foreign_key(None, 'hour_weather', 'hour_data', ['hour_id'], ['hour_id'], source_schema='public', referent_schema='public')
    op.drop_constraint('past_weather_past_id_fkey', 'past_weather', type_='foreignkey')
    op.create_foreign_key(None, 'past_weather', 'past_data', ['past_id'], ['past_id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'past_weather', schema='public', type_='foreignkey')
    op.create_foreign_key('past_weather_past_id_fkey', 'past_weather', 'past_data', ['past_id'], ['past_id'])
    op.drop_constraint(None, 'hour_weather', schema='public', type_='foreignkey')
    op.create_foreign_key('hour_weather_hour_id_fkey', 'hour_weather', 'hour_data', ['hour_id'], ['hour_id'])
    op.drop_column('hour_data', 'show_1h')
    op.drop_column('hour_data', 'rain_1h')
    op.drop_column('hour_data', 'pop')
    op.drop_constraint(None, 'day_weather', schema='public', type_='foreignkey')
    op.create_foreign_key('day_weather_day_id_fkey', 'day_weather', 'day_data', ['day_id'], ['day_id'])
    op.drop_constraint(None, 'day_temperature', schema='public', type_='foreignkey')
    op.create_foreign_key('day_temperature_day_id_fkey', 'day_temperature', 'day_data', ['day_id'], ['day_id'])
    op.drop_constraint(None, 'day_feels_like', schema='public', type_='foreignkey')
    op.create_foreign_key('day_feels_like_day_id_fkey', 'day_feels_like', 'day_data', ['day_id'], ['day_id'])
    op.drop_column('day_data', 'wind_gust')
    # ### end Alembic commands ###
