"""create parent tables

Revision ID: 5b35cabeb899
Revises: 
Create Date: 2022-02-15 08:46:03.086868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b35cabeb899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.Integer(), nullable=True),
    sa.Column('sunrise', sa.Integer(), nullable=True),
    sa.Column('sunset', sa.Integer(), nullable=True),
    sa.Column('moonrise', sa.Integer(), nullable=True),
    sa.Column('moonset', sa.Integer(), nullable=True),
    sa.Column('moon_phase', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('dew_point', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_deg', sa.Float(), nullable=True),
    sa.Column('clouds', sa.Float(), nullable=True),
    sa.Column('pop', sa.Float(), nullable=True),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.Column('snow', sa.Float(), nullable=True),
    sa.Column('uvi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'day_id'),
    schema='public'
    )
    op.create_table('hour_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hour_id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.String(), nullable=True),
    sa.Column('hour_temp', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('dew_point', sa.Float(), nullable=True),
    sa.Column('uvi', sa.Float(), nullable=True),
    sa.Column('clouds', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_deg', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'hour_id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hour_data', schema='public')
    op.drop_table('day_data', schema='public')
    # ### end Alembic commands ###
