"""create past tables

Revision ID: 5f1bc06ab7ff
Revises: c15bc5ae9018
Create Date: 2022-02-16 10:41:01.986804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1bc06ab7ff'
down_revision = 'c15bc5ae9018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('past_id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.Integer(), nullable=True),
    sa.Column('sunrise', sa.Integer(), nullable=True),
    sa.Column('sunset', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('dew_point', sa.Float(), nullable=True),
    sa.Column('clouds', sa.Float(), nullable=True),
    sa.Column('uvi', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('wind_deg', sa.Float(), nullable=True),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.Column('snow', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'past_id'),
    sa.UniqueConstraint('past_id'),
    schema='public'
    )
    op.create_table('past_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('past_id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.Column('main', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['past_id'], ['public.past_data.past_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_constraint('day_feels_like_day_id_fkey', 'day_feels_like', type_='foreignkey')
    op.create_foreign_key(None, 'day_feels_like', 'day_data', ['day_id'], ['day_id'], source_schema='public', referent_schema='public')
    op.drop_constraint('day_temperature_day_id_fkey', 'day_temperature', type_='foreignkey')
    op.create_foreign_key(None, 'day_temperature', 'day_data', ['day_id'], ['day_id'], source_schema='public', referent_schema='public')
    op.drop_constraint('day_weather_day_id_fkey', 'day_weather', type_='foreignkey')
    op.create_foreign_key(None, 'day_weather', 'day_data', ['day_id'], ['day_id'], source_schema='public', referent_schema='public')
    op.drop_constraint('hour_weather_hour_id_fkey', 'hour_weather', type_='foreignkey')
    op.create_foreign_key(None, 'hour_weather', 'hour_data', ['hour_id'], ['hour_id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hour_weather', schema='public', type_='foreignkey')
    op.create_foreign_key('hour_weather_hour_id_fkey', 'hour_weather', 'hour_data', ['hour_id'], ['hour_id'])
    op.drop_constraint(None, 'day_weather', schema='public', type_='foreignkey')
    op.create_foreign_key('day_weather_day_id_fkey', 'day_weather', 'day_data', ['day_id'], ['day_id'])
    op.drop_constraint(None, 'day_temperature', schema='public', type_='foreignkey')
    op.create_foreign_key('day_temperature_day_id_fkey', 'day_temperature', 'day_data', ['day_id'], ['day_id'])
    op.drop_constraint(None, 'day_feels_like', schema='public', type_='foreignkey')
    op.create_foreign_key('day_feels_like_day_id_fkey', 'day_feels_like', 'day_data', ['day_id'], ['day_id'])
    op.drop_table('past_weather', schema='public')
    op.drop_table('past_data', schema='public')
    # ### end Alembic commands ###
