"""create tables

Revision ID: bc34e87e7fa0
Revises: 
Create Date: 2022-02-20 12:10:10.325087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc34e87e7fa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_data',
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.Integer(), nullable=True),
    sa.Column('sunrise', sa.Integer(), nullable=True),
    sa.Column('sunset', sa.Integer(), nullable=True),
    sa.Column('moonrise', sa.Integer(), nullable=True),
    sa.Column('moonset', sa.Integer(), nullable=True),
    sa.Column('moon_phase', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('dew_point', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_deg', sa.Float(), nullable=True),
    sa.Column('clouds', sa.Float(), nullable=True),
    sa.Column('pop', sa.Float(), nullable=True),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.Column('snow', sa.Float(), nullable=True),
    sa.Column('uvi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('day_id'),
    schema='public'
    )
    op.create_table('hour_data',
    sa.Column('hour_id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.Integer(), nullable=True),
    sa.Column('hour_temp', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('dew_point', sa.Float(), nullable=True),
    sa.Column('uvi', sa.Float(), nullable=True),
    sa.Column('clouds', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_deg', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('pop', sa.Float(), nullable=True),
    sa.Column('rain_1h', sa.Float(), nullable=True),
    sa.Column('show_1h', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('hour_id'),
    schema='public'
    )
    op.create_table('past_data',
    sa.Column('past_id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.Integer(), nullable=True),
    sa.Column('sunrise', sa.Integer(), nullable=True),
    sa.Column('sunset', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('dew_point', sa.Float(), nullable=True),
    sa.Column('clouds', sa.Float(), nullable=True),
    sa.Column('uvi', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('wind_deg', sa.Float(), nullable=True),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.Column('snow', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('past_id'),
    schema='public'
    )
    op.create_table('day_feels_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('morn', sa.Float(), nullable=True),
    sa.Column('day', sa.Float(), nullable=True),
    sa.Column('eve', sa.Float(), nullable=True),
    sa.Column('night', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['public.day_data.day_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('day_temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('morn', sa.Float(), nullable=True),
    sa.Column('day', sa.Float(), nullable=True),
    sa.Column('day_min', sa.Float(), nullable=True),
    sa.Column('day_max', sa.Float(), nullable=True),
    sa.Column('eve', sa.Float(), nullable=True),
    sa.Column('night', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['public.day_data.day_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('day_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.Column('main', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['public.day_data.day_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('hour_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hour_id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.Column('main', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hour_id'], ['public.hour_data.hour_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('past_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('past_id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.Column('main', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['past_id'], ['public.past_data.past_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('past_weather', schema='public')
    op.drop_table('hour_weather', schema='public')
    op.drop_table('day_weather', schema='public')
    op.drop_table('day_temperature', schema='public')
    op.drop_table('day_feels_like', schema='public')
    op.drop_table('past_data', schema='public')
    op.drop_table('hour_data', schema='public')
    op.drop_table('day_data', schema='public')
    # ### end Alembic commands ###
